#!/usr/bin/perl
use warnings;
use strict;
use v5.010;

&check_requirements;
if ((! defined $ARGV[0]) || ($ARGV[0] eq '')) {
    &print_usage;
}

sub print_usage {
    say "Usage: " . $0 . " <nhentai.net album URL>";
    say "   Ex: " . $0 . " https://nhentai.net/g/190129/";
    exit 1;
}

sub check_requirements {
    for (qw / egrep curl wget /) {
        my $str = qx % which "$_" %;
        if (length($str) < 1) {
            say "$_ is required to run this program.";
            exit 1;
        }
    }
}

my $BODY = qx % curl -s "$ARGV[0]" | grep -Eo '<div>[0-9]+ pages<.div>' %;
my $PAGE_COUNT = 0;

if ($BODY =~ /<div>([0-9]+) pages/) {
    $PAGE_COUNT = $1;
}

for my $i (1..$PAGE_COUNT) {
    my $PAGE_URL = "$ARGV[0]" . "$i" . "/";
    my $PAGE_DATA = qx % curl -s "$PAGE_URL" | grep -Eo '<img src=\"[^\"]+\" width=\"[^\"]+\" height=\"[^\"]+\" class=\"fit-horizontal' %;
    if ($PAGE_DATA =~ /<img src=\"([^\"]+)\"\s+width/) {
        qx % wget -qnc "$1" %;
    }
}
